# Clean and don't fail
install:
  - rm -rf public || exit 0

# Build the website
script:
  - ./binaries/hugo

branches:
  only:
    - source

# Deploy to GitHub pages
deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip_cleanup: true
  local_dir: public
  target_branch: master
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: source
